Repository PigMa-HaruSari/be15-4th-PigMa-HaruSari, pull requests merged in 2025-05, with the labels that each got.

#6 chore: 프로젝트에 필요한 의존성을 build.gradle에 추가 (#5)
  backend/build.gradle
Labels: ⚙ 설정

#8 feat: application.yml에 mybatis 옵션 설정 및 서버 포트를 환경 변수로 처리하도록 수정 (#7)
  backend/src/main/resources/application.yml
Labels: ⚙ 설정

#10 ci: GitHub Actions를 이용한 PR 테스트 자동화 설정 (#9)
  .github/workflows/ci.yml
  backend/src/test/java/com/pigma/harusari/BackendApplicationTests.java
Labels: ci/cd, ✔️ 테스트

#15 feat : 매일 미달성한 할 일 알림 (#2)
  backend/build.gradle
  backend/src/main/java/com/pigma/harusari/alarm/command/dto/AlarmCreateDto.java
  backend/src/main/java/com/pigma/harusari/alarm/command/entity/Alarm.java
  backend/src/main/java/com/pigma/harusari/alarm/command/repository/AlarmRepository.java
  backend/src/main/java/com/pigma/harusari/alarm/command/scheduler/AlarmScheduler.java
  backend/src/main/java/com/pigma/harusari/alarm/command/service/AlarmService.java
  backend/src/main/java/com/pigma/harusari/alarm/config/RabbitMQConfig.java
  backend/src/main/java/com/pigma/harusari/alarm/config/SchedulerConfig.java
  backend/src/main/java/com/pigma/harusari/alarm/listener/AlarmListener.java
  backend/src/main/java/com/pigma/harusari/alarm/query/mapper/ScheduleQueryMapper.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/SseController.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/SseService.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/TestController.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/mappers/alarm/ScheduleQueryMapper.xml
Labels: 🤖 기능

#16 feat: 일일, 월별, 카테고리별 통계 API 구현 (#14)
  .github/workflows/ci.yml
  backend/src/main/java/com/pigma/harusari/statistics/common/StatisticsType.java
  backend/src/main/java/com/pigma/harusari/statistics/query/controller/StatisticsController.java
  backend/src/main/java/com/pigma/harusari/statistics/query/dto/response/StatisticsCategoryRateResponse.java
  backend/src/main/java/com/pigma/harusari/statistics/query/dto/response/StatisticsCategoryResponse.java
  backend/src/main/java/com/pigma/harusari/statistics/query/dto/response/StatisticsDailyRateResponse.java
  backend/src/main/java/com/pigma/harusari/statistics/query/dto/response/StatisticsDayResponse.java
  backend/src/main/java/com/pigma/harusari/statistics/query/dto/response/StatisticsMonthResponse.java
  backend/src/main/java/com/pigma/harusari/statistics/query/dto/response/StatisticsMonthlyRateResponse.java
  backend/src/main/java/com/pigma/harusari/statistics/query/exception/InvalidDateFormatException.java
  backend/src/main/java/com/pigma/harusari/statistics/query/exception/MissingDateException.java
  backend/src/main/java/com/pigma/harusari/statistics/query/exception/StatisticsErrorCode.java
  backend/src/main/java/com/pigma/harusari/statistics/query/exception/handler/StatisticsExceptionHandler.java
  backend/src/main/java/com/pigma/harusari/statistics/query/mapper/StatisticsMapper.java
  backend/src/main/java/com/pigma/harusari/statistics/query/service/StatisticsService.java
  backend/src/main/java/com/pigma/harusari/statistics/query/service/StatisticsServiceImpl.java
  backend/src/main/java/com/pigma/harusari/statistics/query/utils/StatisticsRequestParser.java
  backend/src/main/resources/mappers/statistics/StatisticsMapper.xml
  backend/src/test/java/com/pigma/harusari/statistics/query/controller/StatisticsControllerTest.java
  backend/src/test/java/com/pigma/harusari/statistics/query/service/StatisticsServiceImplTest.java
  backend/src/test/java/com/pigma/harusari/statistics/query/utils/StatisticsRequestParserTest.java
Labels: 🤖 기능

#23 refactor: 통계 컨트롤러 내 상수명과 에러 코드 리팩토링
  backend/src/main/java/com/pigma/harusari/statistics/query/controller/StatisticsController.java
  backend/src/main/java/com/pigma/harusari/statistics/query/exception/StatisticsErrorCode.java
Labels: ♻️ 리팩토링

#24 feat : 매달 전체적인 달성률 알림 발송 (#4)
  backend/src/main/java/com/pigma/harusari/alarm/command/scheduler/AlarmScheduler.java
  backend/src/main/java/com/pigma/harusari/alarm/query/mapper/ScheduleQueryMapper.java
  backend/src/main/resources/static/mappers/alarm/ScheduleQueryMapper.xml
Labels: 🤖 기능

#28 feat : 안 읽은 알림 목록 조회
  backend/src/main/java/com/pigma/harusari/alarm/query/controller/AlarmQueryController.java
  backend/src/main/java/com/pigma/harusari/alarm/query/dto/AlarmResponseDto.java
  backend/src/main/java/com/pigma/harusari/alarm/query/mapper/AlarmQueryMapper.java
  backend/src/main/java/com/pigma/harusari/alarm/query/service/AlarmQueryService.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/SseController.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/TestController.java
  backend/src/main/resources/mappers/alarm/AlarmQueryMapper.xml
  backend/src/main/resources/mappers/alarm/ScheduleQueryMapper.xml
Labels: ♻️ 리팩토링, 🤖 기능

#29 feat: 이메일 인증 기반 회원가입 및 JWT 인증 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/pigma/harusari/category/command/dto/CategoryCreateRequest.java
  backend/src/main/java/com/pigma/harusari/category/command/entity/Category.java
  backend/src/main/java/com/pigma/harusari/category/command/repository/CategoryCommandRepository.java
  backend/src/main/java/com/pigma/harusari/common/auth/controller/AuthController.java
  backend/src/main/java/com/pigma/harusari/common/auth/dto/LoginRequest.java
  backend/src/main/java/com/pigma/harusari/common/auth/dto/LoginResponse.java
  backend/src/main/java/com/pigma/harusari/common/auth/dto/TokenResponse.java
  backend/src/main/java/com/pigma/harusari/common/auth/entity/RefreshToken.java
  backend/src/main/java/com/pigma/harusari/common/auth/exception/AuthErrorCode.java
  backend/src/main/java/com/pigma/harusari/common/auth/exception/LogInMemberNotFoundException.java
  backend/src/main/java/com/pigma/harusari/common/auth/exception/LogInPasswordMismatchException.java
  backend/src/main/java/com/pigma/harusari/common/auth/exception/RefreshMemberNotFoundException.java
  backend/src/main/java/com/pigma/harusari/common/auth/exception/RefreshTokenInvalidException.java
  backend/src/main/java/com/pigma/harusari/common/auth/exception/handler/AuthExceptionHandler.java
  backend/src/main/java/com/pigma/harusari/common/auth/service/AuthService.java
  backend/src/main/java/com/pigma/harusari/common/auth/service/AuthServiceImpl.java
  backend/src/main/java/com/pigma/harusari/common/auth/service/CustomUserDetailsService.java
  backend/src/main/java/com/pigma/harusari/common/config/RedisConfig.java
  backend/src/main/java/com/pigma/harusari/common/config/SecurityConfig.java
  backend/src/main/java/com/pigma/harusari/common/email/controller/EmailAuthController.java
  backend/src/main/java/com/pigma/harusari/common/email/dto/EmailRequest.java
  backend/src/main/java/com/pigma/harusari/common/email/service/EmailAuthService.java
  backend/src/main/java/com/pigma/harusari/common/service/CustomUserDetailsService.java
  backend/src/main/java/com/pigma/harusari/user/command/controller/UserCommandController.java
  backend/src/main/java/com/pigma/harusari/user/command/dto/SignUpRequest.java
  backend/src/main/java/com/pigma/harusari/user/command/entity/Gender.java
  backend/src/main/java/com/pigma/harusari/user/command/entity/Member.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/CategoryRequiredException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/EmailDuplicatedException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/EmailVerificationFailedException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/NicknameRequiredException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/UserCommandErrorCode.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/handler/UserCommandExceptionHandler.java
  backend/src/main/java/com/pigma/harusari/user/command/repository/UserCommandRepository.java
  backend/src/main/java/com/pigma/harusari/user/command/service/UserCommandService.java
  backend/src/main/java/com/pigma/harusari/user/command/service/UserCommandServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/pigma/harusari/common/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/pigma/harusari/common/auth/service/AuthServiceImplTest.java
  backend/src/test/java/com/pigma/harusari/user/command/controller/UserCommandControllerTest.java
  backend/src/test/java/com/pigma/harusari/user/command/service/UserCommandServiceImplTest.java
Labels: 🤖 기능

#34 refactor: 카테고리 테이블의 member_uid 컬럼명을 member_id로 변경 (#33)
  backend/src/main/resources/mappers/statistics/StatisticsMapper.xml
Labels: ♻️ 리팩토링

#35 feat: Vue 프로젝트 생성
  backend/gradlew
  frontend/.gitignore
  frontend/.vscode/extensions.json
  frontend/README.md
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/css/header.css
  frontend/src/assets/icons/HARURAMENSARI.png
  frontend/src/components/common/Calendar.vue
  frontend/src/components/layout/Header.vue
  frontend/src/features/statistics/components/CategoryStatistics.vue
  frontend/src/features/statistics/components/DailyStatistics.vue
  frontend/src/features/statistics/components/MonthlyStatistics.vue
  frontend/src/features/statistics/router.js
  frontend/src/features/statistics/views/StatisticsView.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/counter.js
  frontend/vite.config.js
Labels: ⚙ 설정

#39 fix: main.css import 삭제
  frontend/src/main.js
Labels: 🐞 버그

#42 fix: 통계 쿼리에서 잘못된 컬럼명 수정 (c.name → c.category_name)
  backend/src/main/resources/mappers/statistics/StatisticsMapper.xml
Labels: 🐞 버그

#41 feat: 카테고리 / 회고 CRUD 기능 구현
  backend/src/main/java/com/pigma/harusari/category/command/application/controller/CategoryCommandController.java
  backend/src/main/java/com/pigma/harusari/category/command/application/dto/request/CategoryCreateRequest.java
  backend/src/main/java/com/pigma/harusari/category/command/application/dto/request/CategoryUpdateRequest.java
  backend/src/main/java/com/pigma/harusari/category/command/application/dto/response/CategoryCommandResponse.java
  backend/src/main/java/com/pigma/harusari/category/command/domain/aggregate/Category.java
  backend/src/main/java/com/pigma/harusari/category/command/domain/repository/CategoryCommandRepository.java
  backend/src/main/java/com/pigma/harusari/category/command/domain/service/CategoryCommandService.java
  backend/src/main/java/com/pigma/harusari/category/command/domain/service/CategoryCommandServiceImpl.java
  backend/src/main/java/com/pigma/harusari/category/command/dto/CategoryCreateRequest.java
  backend/src/main/java/com/pigma/harusari/category/command/entity/Category.java
  backend/src/main/java/com/pigma/harusari/category/command/repository/CategoryCommandRepository.java
  backend/src/main/java/com/pigma/harusari/category/query/controller/CategoryQueryController.java
  backend/src/main/java/com/pigma/harusari/category/query/dto/response/CategoryResponse.java
  backend/src/main/java/com/pigma/harusari/category/query/mapper/CategoryMapper.java
  backend/src/main/java/com/pigma/harusari/category/query/service/CategoryQueryService.java
  backend/src/main/java/com/pigma/harusari/category/query/service/CategoryQueryServiceImpl.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/controller/DiaryCommandController.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/dto/request/DiaryCreateRequest.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/dto/request/DiaryUpdateRequest.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/service/DiaryCommandService.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/service/DiaryCommandServiceImpl.java
  backend/src/main/java/com/pigma/harusari/diary/command/domain/aggregate/Diary.java
  backend/src/main/java/com/pigma/harusari/diary/command/domain/repository/DiaryRepository.java
  backend/src/main/java/com/pigma/harusari/user/command/dto/SignUpRequest.java
  backend/src/main/java/com/pigma/harusari/user/command/service/UserCommandServiceImpl.java
  backend/src/main/resources/mappers/category/CategoryMapper.xml
  backend/src/test/java/com/pigma/harusari/user/command/controller/UserCommandControllerTest.java
  backend/src/test/java/com/pigma/harusari/user/command/service/UserCommandServiceImplTest.java
Labels: 🤖 기능

#43 feat: 개인정보 조회 기능 구현 및 회원 테이블 변경 반영
  backend/src/main/java/com/pigma/harusari/user/command/dto/SignUpRequest.java
  backend/src/main/java/com/pigma/harusari/user/command/entity/Member.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/ConsentRequiredException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/UserCommandErrorCode.java
  backend/src/main/java/com/pigma/harusari/user/command/service/UserCommandServiceImpl.java
  backend/src/main/java/com/pigma/harusari/user/query/controller/UserQueryController.java
  backend/src/main/java/com/pigma/harusari/user/query/dto/UserProfileResponse.java
  backend/src/main/java/com/pigma/harusari/user/query/repository/UserQueryRepository.java
  backend/src/main/java/com/pigma/harusari/user/query/service/UserQueryService.java
  backend/src/main/java/com/pigma/harusari/user/query/service/UserQueryServiceImpl.java
  backend/src/test/java/com/pigma/harusari/user/command/controller/UserCommandControllerTest.java
  backend/src/test/java/com/pigma/harusari/user/command/service/UserCommandServiceImplTest.java
  backend/src/test/java/com/pigma/harusari/user/query/controller/UserQueryControllerTest.java
  backend/src/test/java/com/pigma/harusari/user/query/service/UserQueryServiceImplTest.java
Labels: 🔨 수정, 🤖 기능

#48 feat: CustomUserDetails 구현 및 Spring Security 인증 구조 개선
  backend/src/main/java/com/pigma/harusari/alarm/command/controller/AlarmCommandController.java
  backend/src/main/java/com/pigma/harusari/alarm/query/controller/AlarmQueryController.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/SseController.java
  backend/src/main/java/com/pigma/harusari/common/auth/model/CustomUserDetails.java
  backend/src/main/java/com/pigma/harusari/common/auth/service/CustomUserDetailsService.java
  backend/src/main/java/com/pigma/harusari/common/config/SecurityConfig.java
  backend/src/main/java/com/pigma/harusari/user/query/controller/UserQueryController.java
  backend/src/test/java/com/pigma/harusari/alarm/command/controller/AlarmCommandControllerTest.java
  backend/src/test/java/com/pigma/harusari/alarm/query/controller/AlarmQueryControllerTest.java
  backend/src/test/java/com/pigma/harusari/alarm/sse/SseControllerTest.java
  backend/src/test/java/com/pigma/harusari/support/MemberTestFactory.java
  backend/src/test/java/com/pigma/harusari/support/WithMockCustomUser.java
  backend/src/test/java/com/pigma/harusari/support/WithMockCustomUserSecurityContextFactory.java
  backend/src/test/java/com/pigma/harusari/user/query/controller/UserQueryControllerTest.java
Labels: ♻️ 리팩토링, ✔️ 테스트, 🤖 기능

#52 feat: 일일, 월별, 카테고리별 통계 차트 기능 구현
  frontend/.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/images/HARURAMENSARI.png
  frontend/src/assets/images/header-bell-white.svg
  frontend/src/assets/images/header-bell.svg
  frontend/src/assets/images/header-categories-white.svg
  frontend/src/assets/images/header-categories.svg
  frontend/src/assets/images/header-profile-white.svg
  frontend/src/assets/images/header-profile.svg
  frontend/src/assets/images/header-statistics-white.svg
  frontend/src/assets/images/header-statistics.svg
  frontend/src/features/statistics/components/CategoryStatistics.vue
  frontend/src/features/statistics/components/DailyStatistics.vue
  frontend/src/features/statistics/components/MonthlyStatistics.vue
  frontend/src/features/statistics/views/StatisticsView.vue
  frontend/src/lib/api.js
  frontend/src/main.js
  frontend/src/router/index.js
Labels: 🤖 기능

#56 feat : 메인페이지 및 로그인 기능 구현
  frontend/.prettierrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/css/header.css
  frontend/src/components/layout/Header.vue
  frontend/src/features/main/mainApi.js
  frontend/src/features/main/router.js
  frontend/src/features/main/views/MainPageView.vue
  frontend/src/features/statistics/views/StatisticsView.vue
  frontend/src/features/user/router.js
  frontend/src/features/user/views/LoginView.vue
  frontend/src/lib/api.js
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/userStore.js
Labels: 🤖 기능

#57 feat: 마이페이지 command 기능 구현
  backend/src/main/java/com/pigma/harusari/user/command/controller/UserCommandController.java
  backend/src/main/java/com/pigma/harusari/user/command/dto/SignOutRequest.java
  backend/src/main/java/com/pigma/harusari/user/command/dto/UpdatePasswordRequest.java
  backend/src/main/java/com/pigma/harusari/user/command/dto/UpdateUserProfileRequest.java
  backend/src/main/java/com/pigma/harusari/user/command/entity/Member.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/AlreadySignedOutMemberException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/CurrentPasswordIncorrectException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/EmptyUpdateRequestException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/NewPasswordMismatchException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/PasswordLengthInvalidException.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/UserCommandErrorCode.java
  backend/src/main/java/com/pigma/harusari/user/command/exception/handler/UserCommandExceptionHandler.java
  backend/src/main/java/com/pigma/harusari/user/command/service/UserCommandService.java
  backend/src/main/java/com/pigma/harusari/user/command/service/UserCommandServiceImpl.java
  backend/src/test/java/com/pigma/harusari/user/command/controller/UserCommandControllerTest.java
  backend/src/test/java/com/pigma/harusari/user/command/service/UserCommandServiceImplTest.java
Labels: 🤖 기능

#63 refactor: StatisticsController에서 인증 사용자 정보를 @AuthenticationPrincipal로 주입하도록 리팩토링
  backend/src/main/java/com/pigma/harusari/statistics/query/controller/StatisticsController.java
  backend/src/test/java/com/pigma/harusari/statistics/query/controller/StatisticsControllerTest.java
Labels: ♻️ 리팩토링

#65 chore: springdoc-openapi 2.7.0 버전으로 업그레이드 및 SwaggerConfig 설정 추가
  backend/build.gradle
  backend/src/main/java/com/pigma/harusari/common/config/SecurityConfig.java
  backend/src/main/java/com/pigma/harusari/common/config/SwaggerConfig.java
Labels: ⚙ 설정

#67 docs: 통계 API 명세 작성을 위한 Swagger 어노테이션 적용
  backend/src/main/java/com/pigma/harusari/statistics/query/controller/StatisticsController.java
Labels: 📝 문서

#72 feat : 카테고리 CRUD 및 로그인 로그아웃 기능 구현
  backend/src/main/java/com/pigma/harusari/category/command/application/controller/CategoryCommandController.java
  backend/src/main/java/com/pigma/harusari/category/command/domain/service/CategoryCommandService.java
  backend/src/main/java/com/pigma/harusari/category/command/domain/service/CategoryCommandServiceImpl.java
  backend/src/main/java/com/pigma/harusari/category/query/controller/CategoryQueryController.java
  backend/src/main/java/com/pigma/harusari/common/auth/service/AuthServiceImpl.java
  backend/src/main/java/com/pigma/harusari/common/jwt/JwtTokenProvider.java
  backend/src/main/java/com/pigma/harusari/common/oauth/service/KakaoAuthServiceImpl.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/controller/DiaryCommandController.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/service/DiaryCommandService.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/service/DiaryCommandServiceImpl.java
  backend/src/test/java/com/pigma/harusari/common/auth/service/AuthServiceImplTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/layout/Header.vue
  frontend/src/features/category/categoryApi.js
  frontend/src/features/category/components/CategoryActionModal.vue
  frontend/src/features/category/components/CategoryCreateModal.vue
  frontend/src/features/category/router.js
  frontend/src/features/category/views/CategoryView.vue
  frontend/src/features/main/mainApi.js
  frontend/src/features/main/views/MainPageView.vue
  frontend/src/features/statistics/components/CategoryStatistics.vue
  frontend/src/features/statistics/components/DailyStatistics.vue
  frontend/src/features/statistics/components/MonthlyStatistics.vue
  frontend/src/features/user/views/LoginView.vue
  frontend/src/lib/api.js
  frontend/src/lib/user.js
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/userStore.js
  frontend/src/utill/toast.js
Labels: 🤖 기능

#74 feat : 카테고리 등록 / 수정 사용자 지정 색상 추가
  frontend/src/App.vue
  frontend/src/components/layout/Header.vue
  frontend/src/features/category/components/CategoryCreateModal.vue
  frontend/src/features/category/views/CategoryView.vue
  frontend/src/features/user/router.js
  frontend/src/features/user/views/LoginView.vue
  frontend/src/features/user/views/SignupView.vue
  frontend/src/router/index.js
Labels: 🤖 기능

#83 feat : 피드백 Gemini API 연동 및 피드백 제공
  .idea/.gitignore
  .idea/be15-4th-PigMa-HaruSari.iml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/backend.main.iml
  .idea/modules/backend.test.iml
  .idea/vcs.xml
  backend/build.gradle
  backend/src/main/java/com/pigma/harusari/alarm/query/controller/AlarmQueryController.java
  backend/src/main/java/com/pigma/harusari/common/config/SecurityConfig.java
  backend/src/main/java/com/pigma/harusari/diary/query/mapper/DiaryQueryMapper.java
  backend/src/main/java/com/pigma/harusari/feedback/command/Scheduler/MonthlyFeedbackScheduler.java
  backend/src/main/java/com/pigma/harusari/feedback/command/entity/Feedback.java
  backend/src/main/java/com/pigma/harusari/feedback/command/repository/FeedbackRepository.java
  backend/src/main/java/com/pigma/harusari/feedback/command/service/FeedbackCommandService.java
  backend/src/main/java/com/pigma/harusari/feedback/command/service/FeedbackCommandServiceImpl.java
  backend/src/main/java/com/pigma/harusari/feedback/query/controller/FeedbackQueryController.java
  backend/src/main/java/com/pigma/harusari/feedback/query/dto/FeedbackDetailDto.java
  backend/src/main/java/com/pigma/harusari/feedback/query/dto/FeedbackSummaryDto.java
  backend/src/main/java/com/pigma/harusari/feedback/query/mapper/FeedbackQueryMapper.java
  backend/src/main/java/com/pigma/harusari/feedback/query/service/FeedbackQueryService.java
  backend/src/main/java/com/pigma/harusari/feedback/query/service/FeedbackQueryServiceImpl.java
  backend/src/main/java/com/pigma/harusari/feedback/util/FeedbackPromptBuilder.java
  backend/src/main/java/com/pigma/harusari/feedback/util/GeminiClient.java
  backend/src/main/java/com/pigma/harusari/task/schedule/query/mapper/TaskScheduleQueryMapper.java
  backend/src/main/java/com/pigma/harusari/user/query/mapper/UserQueryMapper.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mappers/diary/DiaryQueryMapper.xml
  backend/src/main/resources/mappers/feedback/FeedbackQueryMapper.xml
  backend/src/main/resources/mappers/schedule/TaskScheduleQueryMapper.xml
  backend/src/main/resources/mappers/user/UserQueryMapper.xml
Labels: 🤖 기능

#84 refactor: 로그인 및 인증 구조 개선 및 localStorage 책임 분리
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/layout/Header.vue
  frontend/src/features/category/categoryApi.js
  frontend/src/features/main/mainApi.js
  frontend/src/features/statistics/components/CategoryStatistics.vue
  frontend/src/features/statistics/components/DailyStatistics.vue
  frontend/src/features/statistics/components/MonthlyStatistics.vue
  frontend/src/features/user/api.js
  frontend/src/features/user/router.js
  frontend/src/features/user/views/LoginView.vue
  frontend/src/lib/axios.js
  frontend/src/lib/user.js
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/counter.js
  frontend/src/stores/userStore.js
Labels: ♻️ 리팩토링

#91 fix: 로그인 후 리다이렉트 및 회원가입 인증 흐름 버그 수정
  frontend/src/features/category/router.js
  frontend/src/features/main/router.js
  frontend/src/features/statistics/router.js
  frontend/src/features/user/api.js
  frontend/src/features/user/router.js
  frontend/src/features/user/views/LoginView.vue
  frontend/src/features/user/views/SignupInfoView.vue
  frontend/src/features/user/views/SignupView.vue
  frontend/src/lib/axios.js
  frontend/src/router/index.js
  frontend/src/stores/signupStore.js
  frontend/src/stores/userStore.js
Labels: 🐞 버그, 🤖 기능

#94 refactor : .yml
  backend/src/main/java/com/pigma/harusari/common/config/SecurityConfig.java
  backend/src/main/java/com/pigma/harusari/diary/query/dto/DiaryResponseDto.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mappers/schedule/TaskScheduleQueryMapper.xml
Labels: ♻️ 리팩토링

#95 feat : 메인 페이지 주요 기능 구현
  frontend/src/components/layout/Header.vue
  frontend/src/features/category/components/CategoryCreateModal.vue
  frontend/src/features/category/views/CategoryView.vue
  frontend/src/features/main/components/AddTaskModal.vue
  frontend/src/features/main/mainApi.js
  frontend/src/features/main/views/MainPageView.vue
  frontend/src/lib/axios.js
Labels: 🤖 기능

#99 feat : 통계 api호출부 기능 수정
  frontend/src/features/category/views/CategoryView.vue
  frontend/src/features/statistics/components/CategoryStatistics.vue
  frontend/src/features/statistics/components/DailyStatistics.vue
  frontend/src/features/statistics/components/MonthlyStatistics.vue
  frontend/src/features/statistics/statisticsApi.js
  frontend/src/features/statistics/views/StatisticsView.vue
Labels: 🔨 수정

#104 feat: 프론트, 백엔드 Dockerfile 및 nginx.conf 파일 생성
  backend/Dockerfile
  frontend/Dockerfile
  frontend/nginx.conf
Labels: ci/cd, ♻️ 리팩토링

#116 feat : [알림/카테고리] SSE 기능 구현 / 카테고리 삭제 구현
  backend/src/main/java/com/pigma/harusari/alarm/sse/SseController.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/SseService.java
  backend/src/main/java/com/pigma/harusari/alarm/sse/TestController.java
  backend/src/main/java/com/pigma/harusari/category/command/domain/service/CategoryCommandServiceImpl.java
  backend/src/main/java/com/pigma/harusari/common/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/pigma/harusari/diary/query/dto/DiaryResponseDto.java
  backend/src/main/resources/mappers/diary/DiaryQueryMapper.xml
  backend/src/test/java/com/pigma/harusari/category/command/domain/service/CategoryCommandServiceImplTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/common/ConfirmModal.vue
  frontend/src/components/common/ConfirmWithInputModal.vue
  frontend/src/components/layout/Header.vue
  frontend/src/features/alarm/NotificationDropDown.vue
  frontend/src/features/alarm/alarmApi.js
  frontend/src/features/category/categoryApi.js
  frontend/src/features/category/components/CategoryCreateModal.vue
  frontend/src/features/category/views/CategoryView.vue
  frontend/src/features/main/components/AddTaskModal.vue
  frontend/src/features/main/mainApi.js
  frontend/src/features/main/views/MainPageView.vue
  frontend/src/features/user/views/LoginView.vue
  frontend/src/utill/connectSSE.js
  frontend/src/utill/emitter.js
Labels: 🤖 기능

#118 hotfix : 로그인 시 리다이렉트 안되는 문제 해결
  frontend/index.html
  frontend/src/features/main/views/MainPageView.vue
  frontend/src/features/user/views/LoginView.vue
Labels: 🐞 버그

#126 feat : 회고 수정 및 삭제 / 과거 데이터 수정 불가 기능
  backend/src/main/java/com/pigma/harusari/category/command/domain/aggregate/Category.java
  backend/src/main/java/com/pigma/harusari/diary/command/application/controller/DiaryCommandController.java
  frontend/src/features/category/categoryApi.js
  frontend/src/features/category/components/CategoryActionModal.vue
  frontend/src/features/category/views/CategoryView.vue
  frontend/src/features/main/components/EditTaskModal.vue
  frontend/src/features/main/mainApi.js
  frontend/src/features/main/views/MainPageView.vue
Labels: 🤖 기능

#137 feat : 자동화 일정 등록 / 피드백 목록 & 상세 조회 기능 구현 / 이.스.터.에.그
  backend/src/main/java/com/pigma/harusari/feedback/query/controller/FeedbackQueryController.java
  backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleServiceImpl.java
  backend/src/main/java/com/pigma/harusari/task/automationSchedule/query/dto/response/AutomationScheduleDto.java
  backend/src/main/resources/mappers/schedule/AutomationScheduleMapper.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/common/ConfirmWithInputModal.vue
  frontend/src/features/EasterEgg/router.js
  frontend/src/features/EasterEgg/views/EasterEgg2048GameView.vue
  frontend/src/features/category/views/CategoryView.vue
  frontend/src/features/feedback/feedbackApi.js
  frontend/src/features/feedback/router.js
  frontend/src/features/feedback/views/FeedbackView.vue
  frontend/src/features/main/automationScheduleApi.js
  frontend/src/features/main/components/AddTaskModal.vue
  frontend/src/features/main/components/AutomationScheduleForm.vue
  frontend/src/features/main/components/AutomationScheduleModal.vue
  frontend/src/features/main/mainApi.js
  frontend/src/features/main/views/MainPageView.vue
  frontend/src/router/index.js
Labels: 🤖 기능

#146 hotfix : 버그 수정
  backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/controller/AutomationScheduleController.java
  backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/entity/AutomationSchedule.java
  backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleService.java
  backend/src/main/java/com/pigma/harusari/task/automationSchedule/command/service/AutomationScheduleServiceImpl.java
  backend/src/main/java/com/pigma/harusari/task/automationSchedule/query/dto/response/AutomationScheduleDto.java
  backend/src/main/resources/mappers/schedule/AutomationScheduleMapper.xml
  frontend/src/features/main/components/EditTaskModal.vue
  frontend/src/features/main/views/MainPageView.vue
Labels: 🐞 버그

#151 docs: jenkins 파이프라인에서 불필요한 코드 삭제
  README.md
Labels: 📝 문서
